#!/usr/bin/env python3
"""Provenance guard for data posts (dependency-free).

Two checks, so a hallucinated number or a fabricated link fails the build
instead of reaching a reader:

1. LINK RESOLUTION. Every commit-pinned GitHub blob URL in any post
   (github.com/<owner>/<repo>/blob/<40-hex-sha>/<path>) must resolve. A typo'd
   SHA, a wrong path, or an invented citation 404s here rather than for a reader.
   Confirmed 404 fails the build; a network error only warns (CI stays robust).

2. MANIFEST <-> PROSE. Every post directory that ships a `provenance.json`
   manifest must: be valid JSON of the expected shape; list only figures that
   exist in the bundle; and have every manifest number's `appears_as` string
   present in the post's index.md. The manifest is generated by the experiment
   repo with each number RE-DERIVED from a committed receipt, so this binds the
   receipt-derived numbers to what the prose actually says -- edit a number in
   one place but not the other and this fails.

Run from repo root: `python3 scripts/check_provenance.py`.
"""

from __future__ import annotations

import json
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
POSTS = ROOT / "blog-source" / "content" / "posts"
BLOB_RE = re.compile(
    r"https://github\.com/([^/\s)]+)/([^/\s)]+)/blob/([0-9a-f]{40})/([^\s)\"'<>]+)"
)
DASHES = {"–": "-", "—": "-", "−": "-"}


def norm(s: str) -> str:
    for a, b in DASHES.items():
        s = s.replace(a, b)
    return s.replace("**", "").replace("*", "")


def markdown_files() -> list[Path]:
    return sorted(POSTS.rglob("*.md"))


def resolve_url(owner: str, repo: str, sha: str, path: str) -> tuple[str, str]:
    """Return ('ok'|'missing'|'error', detail). Uses raw.githubusercontent (public)."""
    raw = f"https://raw.githubusercontent.com/{owner}/{repo}/{sha}/{path}"
    req = urllib.request.Request(raw, method="HEAD", headers={"User-Agent": "prov-check"})
    for attempt in range(3):
        try:
            with urllib.request.urlopen(req, timeout=15) as resp:
                return ("ok", str(resp.status))
        except urllib.error.HTTPError as e:
            if e.code in (404, 400):
                return ("missing", f"HTTP {e.code}")
            if e.code in (429, 500, 502, 503) and attempt < 2:
                continue
            return ("error", f"HTTP {e.code}")
        except (urllib.error.URLError, TimeoutError, OSError) as e:
            if attempt < 2:
                continue
            return ("error", str(e))
    return ("error", "retries exhausted")


def check_links() -> tuple[int, int]:
    seen: dict[tuple[str, str, str, str], list[str]] = {}
    for md in markdown_files():
        for m in BLOB_RE.finditer(md.read_text(encoding="utf-8")):
            seen.setdefault(m.groups(), []).append(md.name)
    fails = warns = 0
    for (owner, repo, sha, path), where in sorted(seen.items()):
        status, detail = resolve_url(owner, repo, sha, path)
        tag = {"ok": "OK  ", "missing": "FAIL", "error": "WARN"}[status]
        if status == "missing":
            fails += 1
            print(f"{tag} {owner}/{repo}@{sha[:8]} {path} -> {detail} (in {where[0]})")
        elif status == "error":
            warns += 1
            print(f"{tag} {owner}/{repo}@{sha[:8]} {path} -> {detail} (network; not failing)")
    print(f"  links: {len(seen)} pinned URL(s), {fails} unresolved, {warns} unchecked (network)")
    return fails, warns


def check_manifests() -> int:
    fails = 0
    manifests = sorted(POSTS.rglob("provenance.json"))
    if not manifests:
        print("  manifests: none found")
        return 0
    for mf in manifests:
        post = mf.parent
        rel = mf.relative_to(ROOT)
        try:
            man = json.loads(mf.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            fails += 1
            print(f"FAIL {rel}: invalid JSON ({e})")
            continue
        for key in ("generator", "receipts", "figures", "numbers"):
            if key not in man:
                fails += 1
                print(f"FAIL {rel}: missing required key '{key}'")
        idx = post / "index.md"
        prose = norm(idx.read_text(encoding="utf-8")) if idx.exists() else ""
        if not prose:
            fails += 1
            print(f"FAIL {rel}: no index.md beside the manifest")
        for fig in man.get("figures", []):
            if not (post / fig).exists():
                fails += 1
                print(f"FAIL {rel}: figure '{fig}' listed but not in bundle")
        n_ok = 0
        for num in man.get("numbers", []):
            appears = norm(str(num.get("appears_as", "")))
            if not appears or appears not in prose:
                fails += 1
                print(f"FAIL {rel}: number [{num.get('id')}] appears_as "
                      f"'{num.get('appears_as')}' not found in index.md")
            else:
                n_ok += 1
        print(f"  {rel.parent.name}/provenance.json: {n_ok}/{len(man.get('numbers', []))} "
              f"numbers matched in prose, {len(man.get('figures', []))} figures present")
    return fails


def main() -> int:
    print("Provenance check: pinned-link resolution + manifest<->prose")
    link_fails, _ = check_links()
    man_fails = check_manifests()
    total = link_fails + man_fails
    if total:
        print(f"\nProvenance check FAILED: {total} issue(s).")
        return 1
    print("\nProvenance check passed: every pinned link resolves and every "
          "manifest number appears in its post.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
