#!/usr/bin/env python3
"""Provenance guard for data-backed content bundles (dependency-free).

Two checks, so a hallucinated number or a fabricated link fails the build
instead of reaching a reader:

1. LINK RESOLUTION. Every commit-pinned GitHub blob URL in a Research Note or
   Knowledge Base Deep Dive
   (github.com/<owner>/<repo>/blob/<40-hex-sha>/<path>) must resolve. A typo'd
   SHA, a wrong path, or an invented citation 404s here rather than for a reader.
   Confirmed 404 fails the build; a network error only warns (CI stays robust).

2. MANIFEST <-> PROSE. Every content directory that ships a `provenance.json`
   manifest must: be valid JSON of the expected shape; list only figures that
   exist in the bundle; and have every manifest number's `appears_as` string
   present in the post's index.md. The manifest is generated by the experiment
   repo with each number RE-DERIVED from a committed receipt, so this binds the
   receipt-derived numbers to what the prose actually says -- edit a number in
   one place but not the other and this fails. Local bundles also validate
   generator, notebook, receipt, and figure hashes. Set `local_bundle` to true
   or false explicitly to control that strict check; without the flag, a
   manifest whose receipt paths all exist beside it is treated as local.

Run from repo root: `python3 scripts/check_provenance.py`.
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTENT_ROOTS = (
    ROOT / "blog-source" / "content" / "posts",
    ROOT / "blog-source" / "content" / "knowledge-base" / "deep-dives",
)
BLOB_RE = re.compile(
    r"https://github\.com/([^/\s)]+)/([^/\s)]+)/blob/([0-9a-f]{40})/([^\s)\"'<>]+)"
)
SHA256_RE = re.compile(r"[0-9a-f]{64}")
DASHES = {"–": "-", "—": "-", "−": "-"}


def norm(s: str) -> str:
    for a, b in DASHES.items():
        s = s.replace(a, b)
    return s.replace("**", "").replace("*", "")


def markdown_files() -> list[Path]:
    return sorted(path for root in CONTENT_ROOTS for path in root.rglob("*.md"))


def manifest_files() -> list[Path]:
    return sorted(
        path for root in CONTENT_ROOTS for path in root.rglob("provenance.json")
    )


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def local_bundle_path(bundle: Path, raw: object) -> tuple[Path | None, str | None]:
    if not isinstance(raw, str) or not raw:
        return None, "path must be a non-empty string"
    relative = Path(raw)
    if relative.is_absolute():
        return None, "path must be relative to the content bundle"
    resolved = (bundle / relative).resolve()
    try:
        resolved.relative_to(bundle.resolve())
    except ValueError:
        return None, "path escapes the content bundle"
    return resolved, None


def check_sha256(
    manifest: Path,
    bundle: Path,
    raw_path: object,
    expected: object,
    kind: str,
) -> int:
    relative_manifest = manifest.relative_to(ROOT)
    path, error = local_bundle_path(bundle, raw_path)
    if error is not None or path is None:
        print(f"FAIL {relative_manifest}: {kind} {raw_path!r}: {error}")
        return 1
    if not isinstance(expected, str) or SHA256_RE.fullmatch(expected) is None:
        print(
            f"FAIL {relative_manifest}: {kind} {raw_path!r} has invalid SHA-256"
        )
        return 1
    if not path.is_file():
        print(f"FAIL {relative_manifest}: {kind} {raw_path!r} does not exist")
        return 1
    actual = sha256_file(path)
    if actual != expected:
        print(
            f"FAIL {relative_manifest}: {kind} {raw_path!r} SHA-256 mismatch "
            f"(expected {expected}, found {actual})"
        )
        return 1
    return 0


def infer_local_bundle(manifest: dict[object, object], bundle: Path) -> bool:
    if "local_bundle" in manifest:
        return manifest.get("local_bundle") is True
    receipts = manifest.get("receipts")
    if not isinstance(receipts, dict) or not receipts:
        return False
    paths = [local_bundle_path(bundle, raw)[0] for raw in receipts]
    return all(path is not None and path.is_file() for path in paths)


def check_local_hashes(manifest_path: Path, manifest: dict[object, object]) -> int:
    """Validate hashes for a self-contained content bundle."""
    fails = 0
    bundle = manifest_path.parent
    relative_manifest = manifest_path.relative_to(ROOT)

    generator = manifest.get("generator")
    if not isinstance(generator, dict):
        print(f"FAIL {relative_manifest}: local generator must be an object")
        fails += 1
    else:
        fails += check_sha256(
            manifest_path,
            bundle,
            generator.get("path"),
            generator.get("sha256"),
            "generator",
        )

    notebook = manifest.get("notebook")
    if notebook is not None:
        if not isinstance(notebook, dict):
            print(f"FAIL {relative_manifest}: local notebook must be an object")
            fails += 1
        else:
            fails += check_sha256(
                manifest_path,
                bundle,
                notebook.get("path"),
                notebook.get("sha256"),
                "notebook",
            )

    receipts = manifest.get("receipts")
    if not isinstance(receipts, dict):
        print(f"FAIL {relative_manifest}: local receipts must be an object")
        return fails + 1

    figure_hashes: dict[str, str] = {}
    for raw_path, expected_hash in receipts.items():
        fails += check_sha256(
            manifest_path,
            bundle,
            raw_path,
            expected_hash,
            "receipt",
        )
        receipt_path, error = local_bundle_path(bundle, raw_path)
        if (
            error is not None
            or receipt_path is None
            or not receipt_path.is_file()
            or not receipt_path.name.startswith("fig-")
            or not receipt_path.name.endswith(".receipt.json")
        ):
            continue
        try:
            receipt = json.loads(receipt_path.read_text(encoding="utf-8"))
        except (UnicodeDecodeError, json.JSONDecodeError) as exc:
            print(
                f"FAIL {relative_manifest}: figure receipt {raw_path!r} is "
                f"invalid JSON ({exc})"
            )
            fails += 1
            continue
        if not isinstance(receipt, dict):
            print(
                f"FAIL {relative_manifest}: figure receipt {raw_path!r} root "
                "must be an object"
            )
            fails += 1
            continue
        provenance = receipt.get("provenance")
        outputs = provenance.get("outputs", {}) if isinstance(provenance, dict) else {}
        if not isinstance(outputs, dict) or not outputs:
            print(
                f"FAIL {relative_manifest}: figure receipt {raw_path!r} "
                "requires provenance.outputs"
            )
            fails += 1
            continue
        for output_path, output_hash in outputs.items():
            fails += check_sha256(
                manifest_path,
                bundle,
                output_path,
                output_hash,
                "figure output",
            )
            if isinstance(output_path, str) and isinstance(output_hash, str):
                figure_hashes[output_path] = output_hash

    figures = manifest.get("figures")
    if isinstance(figures, list):
        for figure in figures:
            if isinstance(figure, str) and figure not in figure_hashes:
                print(
                    f"FAIL {relative_manifest}: local figure {figure!r} is not "
                    "hash-bound by a figure receipt"
                )
                fails += 1
    return fails


def resolve_url(owner: str, repo: str, sha: str, path: str) -> tuple[str, str]:
    """Return ('ok'|'missing'|'error', detail). Uses raw.githubusercontent (public)."""
    raw = f"https://raw.githubusercontent.com/{owner}/{repo}/{sha}/{path}"
    req = urllib.request.Request(raw, method="HEAD", headers={"User-Agent": "prov-check"})
    for attempt in range(3):
        try:
            with urllib.request.urlopen(req, timeout=15) as resp:
                return ("ok", str(resp.status))
        except urllib.error.HTTPError as e:
            if e.code in (404, 400):
                return ("missing", f"HTTP {e.code}")
            if e.code in (429, 500, 502, 503) and attempt < 2:
                continue
            return ("error", f"HTTP {e.code}")
        except (urllib.error.URLError, TimeoutError, OSError) as e:
            if attempt < 2:
                continue
            return ("error", str(e))
    return ("error", "retries exhausted")


def check_links() -> tuple[int, int]:
    seen: dict[tuple[str, str, str, str], list[str]] = {}
    for md in markdown_files():
        for m in BLOB_RE.finditer(md.read_text(encoding="utf-8")):
            seen.setdefault(m.groups(), []).append(md.name)
    fails = warns = 0
    for (owner, repo, sha, path), where in sorted(seen.items()):
        status, detail = resolve_url(owner, repo, sha, path)
        tag = {"ok": "OK  ", "missing": "FAIL", "error": "WARN"}[status]
        if status == "missing":
            fails += 1
            print(f"{tag} {owner}/{repo}@{sha[:8]} {path} -> {detail} (in {where[0]})")
        elif status == "error":
            warns += 1
            print(f"{tag} {owner}/{repo}@{sha[:8]} {path} -> {detail} (network; not failing)")
    print(f"  links: {len(seen)} pinned URL(s), {fails} unresolved, {warns} unchecked (network)")
    return fails, warns


def check_manifests() -> int:
    fails = 0
    manifests = manifest_files()
    if not manifests:
        print("  manifests: none found")
        return 0
    for mf in manifests:
        post = mf.parent
        rel = mf.relative_to(ROOT)
        try:
            man = json.loads(mf.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            fails += 1
            print(f"FAIL {rel}: invalid JSON ({e})")
            continue
        if not isinstance(man, dict):
            fails += 1
            print(f"FAIL {rel}: manifest root must be an object")
            continue
        for key in ("generator", "receipts", "figures", "numbers"):
            if key not in man:
                fails += 1
                print(f"FAIL {rel}: missing required key '{key}'")
        idx = post / "index.md"
        prose = norm(idx.read_text(encoding="utf-8")) if idx.exists() else ""
        if not prose:
            fails += 1
            print(f"FAIL {rel}: no index.md beside the manifest")
        figures = man.get("figures", [])
        if not isinstance(figures, list):
            fails += 1
            print(f"FAIL {rel}: figures must be a list")
            figures = []
        for fig in figures:
            figure_path, error = local_bundle_path(post, fig)
            if error is not None or figure_path is None:
                fails += 1
                print(f"FAIL {rel}: figure {fig!r}: {error}")
            elif not figure_path.is_file():
                fails += 1
                print(f"FAIL {rel}: figure '{fig}' listed but not in bundle")
        n_ok = 0
        numbers = man.get("numbers", [])
        if not isinstance(numbers, list):
            fails += 1
            print(f"FAIL {rel}: numbers must be a list")
            numbers = []
        for num in numbers:
            if not isinstance(num, dict):
                fails += 1
                print(f"FAIL {rel}: each number must be an object")
                continue
            appears = norm(str(num.get("appears_as", "")))
            if not appears or appears not in prose:
                fails += 1
                print(f"FAIL {rel}: number [{num.get('id')}] appears_as "
                      f"'{num.get('appears_as')}' not found in index.md")
            else:
                n_ok += 1
        local_setting = man.get("local_bundle")
        if "local_bundle" in man and not isinstance(local_setting, bool):
            fails += 1
            print(f"FAIL {rel}: local_bundle must be true or false")
        local = infer_local_bundle(man, post)
        if local:
            fails += check_local_hashes(mf, man)
        print(
            f"  {rel.parent.name}/provenance.json: {n_ok}/{len(numbers)} "
            f"numbers matched in prose, {len(figures)} figures present, "
            f"local hashes {'checked' if local else 'not requested'}"
        )
    return fails


def main() -> int:
    print("Provenance check: pinned-link resolution + manifest<->prose")
    link_fails, _ = check_links()
    man_fails = check_manifests()
    total = link_fails + man_fails
    if total:
        print(f"\nProvenance check FAILED: {total} issue(s).")
        return 1
    print("\nProvenance check passed: every pinned link resolves and every "
          "manifest number appears in its content page.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
